### ISSUE TITLE
Misuse of new

### ISSUE THREAD

**Issue by k0001** [nitros12/di-polysemy#1]
Hi! I just came across your [article](https://nitros12.github.io/writing-a-discord-library-using-polysemy). Cool stuff! Thanks for sharing it!

I noticed there, however, a misuse of the `new` function. 

Essentially, `di-polysemy` should **not** be using the `new` function, nor trying to construct a `Di` value at all. Instead, the various `runXxx` functions in your library should take a `Di` value as a parameter. 

You can think of the `Di` value as file handle or `MVar` that will be accessed from multiple places in the application, possibly from different threads, with and without polysemy. If you construct a new `Di` value each time `diToIO` runs, then there's no guarantee that the log messages that are finally rendered to the outside world will happen in an absolute order, and if you attempt to log things from multiple threads you'll most definitely see log messages stepping on each other on `stderr` or similar.

`new` is expected to be used just once, in `main`, as soon as the application starts, and the resulting `Di` value should be given as argument to the various `runXxx` functions, and to the logging functions such as `info`, `notice`, etc. It's perfectly safe to use this one `Di` value, as is, from multiple threads.

As a convenience, to keep things simple in end-user applications (that is, in applications that depend on `di-polysemy`), you'll probably want to call `Di.new` from the `di` package, which is a bit higher-level than `Di.Core.new`.

**Comment by simmsb** [comment]
That makes sense, I'm not sure why I decided to create the Di value myself since passing in the Di value is much simpler.

**Comment by simmsb** [comment]
Okay, I think everything should be sorted now. Thanks
